import { Product } from "./products.types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "ダブルジャケット",
    category: "ジャケット",
    sizes: ["S", "M", "L"],
    thumbnailUrl: "/clothes/double_jacket.png",
    previewImageUrl: "/clothes/double_jacket.png",
    enabled: true,
    searchSegment: "カジュアル",
    season: "24SS",
    status: "公開中",
  },
  {
    id: "2",
    name: "ウールコート",
    category: "コート",
    sizes: ["S", "M", "L"],
    thumbnailUrl: "/clothes/wool_coat.png",
    previewImageUrl: "/clothes/wool_coat.png",
    enabled: true,
    searchSegment: "フォーマル",
    season: "25AW",
    status: "制作中",
  },
  {
    id: "3",
    name: "デニムジャケット",
    category: "ジャケット",
    sizes: ["S", "M", "L"],
    thumbnailUrl: "/clothes/denim_jacket.png",
    previewImageUrl: "/clothes/denim_jacket.png",
    enabled: false,
    searchSegment: "カジュアル",
    season: "24SS",
    status: "レビュー待ち",
  },
  {
    id: "4",
    name: "レザージャケット",
    category: "ジャケット",
    sizes: ["S", "M", "L"],
    thumbnailUrl: "/clothes/leather_jacket.png",
    previewImageUrl: "/clothes/leather_jacket.png",
    enabled: false,
    searchSegment: "カジュアル",
    season: "24AW",
    status: "未発注",
  },
];
